### ISSUE TITLE
Evolution for non PWM pins

### ISSUE THREAD

**Issue by LaurentR59** [jandelgado/jled#107]
Hi
As a so good job require a possible extension to manage non PWM pins...

Should be a real major improvement by a bit banging option for non PWM pins...

May for a futur soon release?

Laurent

**Comment by jandelgado** [comment]
It's already possible to extend JLed with custom HALs (Hardware Abstraction Layers). Examples are here https://github.com/jandelgado/jled/tree/master/examples/custom_hal and here https://github.com/jandelgado/jled-pca9685-hal.  

Proving these custom HALs is however **out of the scope of JLed**, since that functionality would be too hardware specific (what platform should the bit-bang PWM be implemented for?).
